IF not EXISTS (SELECT * FROM SYS.databases WHERE NAME ='PIM5_')
	CREATE DATABASE PIM5_
ELSE
	use master
	DROP DATABASE PIM5_
	go
	CREATE DATABASE PIM5_

GO
USE PIM5_

GO
CREATE TABLE TB_USUARIO
(USU_INT_ID INT PRIMARY KEY IDENTITY,
USU_STR_NOME VARCHAR (100),
USU_STR_CPF CHAR(15),
USU_DT_DTNASCIMENTO DATE,
USU_STR_SEXO CHAR(1),
USU_STR_EMAIL VARCHAR (50),
USU_STR_SENHA VARCHAR(MAX),
USU_STR_STATUS CHAR(1),--P - PENDENTE; A - ATIVO;
USU_STR_TIPO CHAR(1),
USU_DT_DTCADASTRO DATETIME
);

GO
CREATE TABLE TB_MOEDA
(MOE_INT_ID INT PRIMARY KEY IDENTITY,
MOE_STR_DESC VARCHAR(20),
MOE_STR_SIGLA VARCHAR(5),
);
CREATE TABLE TB_CARTEIRA
(CAR_INT_ID INT PRIMARY KEY IDENTITY,
USU_INT_ID INT)
GO
ALTER TABLE TB_CARTEIRA ADD  CONSTRAINT FK_USUARIO_CARTEIRA FOREIGN KEY (USU_INT_ID) REFERENCES TB_USUARIO (USU_INT_ID);


GO
CREATE TABLE TB_TRANSFERENCIA
(TRA_INT_ID INT PRIMARY KEY IDENTITY,
TRA_STR_DESC VARCHAR(70),
TRA_DOU_VALOR DECIMAL(9,2),
TRA_DT_DATATRANS DATE,
TRA_STR_PROTOCOLO VARCHAR(15),
MOE_INT_ID INT,
USU_INT_ID INT
)
go
ALTER TABLE TB_TRANSFERENCIA ADD  CONSTRAINT TB_MOEDA_FK_ID FOREIGN KEY (MOE_INT_ID) REFERENCES TB_MOEDA (MOE_INT_ID);
ALTER TABLE TB_TRANSFERENCIA ADD  CONSTRAINT TB_USUARIO_FK_ID FOREIGN KEY (USU_INT_ID) REFERENCES TB_USUARIO (USU_INT_ID);

GO
CREATE TABLE TB_COTACAO
(
COT_INT_ID INT PRIMARY KEY IDENTITY,
COT_DT_COTA DATE,
COT_DEC_VALORCOT DECIMAL(9,2),
MOE_INT_ID INT
)
GO
ALTER TABLE TB_COTACAO ADD  CONSTRAINT TB_MOED_FK_ID FOREIGN KEY (MOE_INT_ID) REFERENCES TB_MOEDA (MOE_INT_ID);

GO
CREATE TABLE TB_DEPOSITO
(
DEP_INT_ID INT PRIMARY KEY IDENTITY,
DEP_STR_TIPO CHAR(1), --1 - Boleto; 2 - Cartão
DEP_STR_TITULAR VARCHAR(50),
DEP_DT_DTVENC DATE,
DEP_STR_NUMCARTAO VARCHAR(20),
DEP_STR_CVV CHAR(3),
DEP_DT_DTPAG DATE,
DEP_DOU_VALOR DECIMAL(9,2),
DEP_STR_STATUS CHAR(1),
CAR_INT_ID INT,
DEP_STR_PROTOCOLO VARCHAR(15),
DEP_STR_NUMBLT VARCHAR(48),
DEP_STR_CARTAOVENC VARCHAR(7))

GO
ALTER TABLE TB_DEPOSITO ADD  CONSTRAINT FK_CARTEIRA_DEPOSITO FOREIGN KEY (CAR_INT_ID) REFERENCES TB_CARTEIRA (CAR_INT_ID);

GO
CREATE TABLE TB_BACKUP
(
	BAC_INT_ID INT IDENTITY PRIMARY KEY,
	BC_DT_DATA DATETIME,
	BC_STR_DATABASE VARCHAR(30),
	BAC_STR_DIRETORIO VARCHAR(255),
	BAC_STR_STATUS CHAR(1),
	USU_INT_ID INT
);
go
ALTER TABLE TB_BACKUP ADD  CONSTRAINT FK_USUARIO_BACKUP FOREIGN KEY (USU_INT_ID) REFERENCES TB_USUARIO (USU_INT_ID);
GO

GO
CREATE TABLE TB_MOEDA_CARTEIRA
(
	CAR_INT_ID INT,
	MOE_INT_ID INT,
	MC_DEC_SALDO DECIMAL (9,2)
);
GO
ALTER TABLE TB_MOEDA_CARTEIRA ADD  CONSTRAINT TB_MOEDA_CARTEIRA_CAR_ID_FK FOREIGN KEY (CAR_INT_ID) REFERENCES TB_CARTEIRA (CAR_INT_ID);
ALTER TABLE TB_MOEDA_CARTEIRA ADD  CONSTRAINT TB_MOEDA_CARTEIRA_MOE_ID_FK FOREIGN KEY (MOE_INT_ID) REFERENCES TB_MOEDA (MOE_INT_ID);


GO
CREATE TABLE TB_CONVERSAO (
  CON_INT_ID INTEGER IDENTITY PRIMARY KEY,
  USU_INT_ID INTEGER,
  CON_INT_MOE_IN INTEGER,
  CON_INT_MOE_FI INTEGER,
  CON_DEC_VLR_IN DECIMAL(9,2),
  CON_DEC_VLR_FI DECIMAL(9,2),
  CON_STR_PROTO VARCHAR(15) NULL,
  CON_STR_DATA DATE NULL);

ALTER TABLE TB_CONVERSAO ADD  CONSTRAINT TB_CONVERSAO_FK FOREIGN KEY (USU_INT_ID) REFERENCES TB_USUARIO (USU_INT_ID);

GO



/*
View para unir as transações realizadas

autor: José Hugo Soares de Barros
Data: 22/09/2020

Manutenção:
Data: 23/11/2020 autor: José hugo Descrição: ajuste para adicionar o select da tabela de conversao

*/
CREATE VIEW VW_TRANSACOES
AS
SELECT USU.USU_INT_ID AS [USUARIO], 
TR.TRA_STR_PROTOCOLO AS [PROTOCOLO],
TRA_DT_DATATRANS AS [DATA],'TRANSFERENCIA' AS [TIPO],
TRA_DOU_VALOR AS [VALOR],
M.MOE_INT_ID AS [MOEDA] ,
USU.USU_STR_NOME AS [NOME],
TR.TRA_STR_DESC AS [OBSERVACAO]
FROM TB_TRANSFERENCIA TR
INNER JOIN TB_USUARIO USU ON USU.USU_INT_ID = TR.USU_INT_ID
INNER JOIN TB_MOEDA M ON M.MOE_INT_ID = TR.MOE_INT_ID

UNION ALL

SELECT  USU.USU_INT_ID AS [USUARIO],
DEP_STR_PROTOCOLO AS [PROTOCOLO],
DEP_DT_DTPAG AS [DATA],
CASE WHEN DEP_STR_TIPO = 1 THEN 'DEPOSITO - BOLETO' ELSE 'DEPOSITO - CARTAO' END AS [TIPO],
DEP_DOU_VALOR AS [VALOR],2 AS [MOEDA],
USU.USU_STR_NOME AS [NOME],
'REGISTRO GERADO VIA DEPOSITO' AS [OBSERVACAO]
FROM TB_DEPOSITO DEP
INNER JOIN TB_CARTEIRA CAR ON CAR.CAR_INT_ID = DEP.CAR_INT_ID
INNER JOIN TB_USUARIO USU ON USU.USU_INT_ID = CAR.CAR_INT_ID

UNION ALL

SELECT  USU.USU_INT_ID AS [USUARIO],
CON_STR_PROTO AS [PROTOCOLO],
CON_STR_DATA AS [DATA],
'CAMBIO' AS [TIPO],
CON_DEC_VLR_IN AS [VALOR], MOE.MOE_INT_ID AS [MOEDA],
USU.USU_STR_NOME AS [NOME],
'REGISTRO GERADO VIA DEPOSITO' AS [OBSERVACAO]
FROM TB_CONVERSAO CON
INNER JOIN TB_MOEDA MOE ON MOE.MOE_INT_ID = CON.CON_INT_MOE_IN
INNER JOIN TB_USUARIO USU ON USU.USU_INT_ID = CON.USU_INT_ID
